# Generated by Django 5.0 on 2025-11-01 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommandSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Заголовок блока"),
                ),
                (
                    "desc",
                    models.TextField(max_length=800, verbose_name="Описание блока"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=250, verbose_name="Ссылка на блок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Видимость"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Наша команда",
                "verbose_name_plural": "Наша команда",
                "db_table": "section_command_main",
            },
        ),
        migrations.CreateModel(
            name="CommandSectionFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Доп.информация"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="имя"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="должность"
                    ),
                ),
                (
                    "desc",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="описание"
                    ),
                ),
                (
                    "social",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="контакты"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Видимость"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("src", models.ImageField(blank=True, upload_to="")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="%Y/%m/%d/thumbnails"
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Описание картинки"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="command.commandsection",
                    ),
                ),
            ],
            options={
                "db_table": "section_command_features",
            },
        ),
    ]
