# Generated by Django 5.0 on 2026-07-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("command", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandsectionfeatures",
            name="desc",
            field=models.TextField(blank=True, max_length=500, verbose_name="описание"),
        ),
    ]
