# Generated by Django 5.0 on 2026-07-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("command", "0002_alter_commandsectionfeatures_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commandsectionfeatures",
            name="alt",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Описание картинки"
            ),
        ),
        migrations.AlterField(
            model_name="commandsectionfeatures",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="имя"),
        ),
        migrations.AlterField(
            model_name="commandsectionfeatures",
            name="social",
            field=models.CharField(blank=True, max_length=255, verbose_name="контакты"),
        ),
        migrations.AlterField(
            model_name="commandsectionfeatures",
            name="src",
            field=models.ImageField(blank=True, max_length=255, upload_to=""),
        ),
        migrations.AlterField(
            model_name="commandsectionfeatures",
            name="status",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="должность"
            ),
        ),
        migrations.AlterField(
            model_name="commandsectionfeatures",
            name="thumbnail",
            field=models.ImageField(
                blank=True, max_length=255, null=True, upload_to="%Y/%m/%d/thumbnails"
            ),
        ),
        migrations.AlterField(
            model_name="commandsectionfeatures",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Доп.информация"
            ),
        ),
    ]
