services:
  web:
    build:
      context: ./deploy
      dockerfile: ./Dockerfile
    user: "${APP_UID:-1000}:${APP_GID:-1000}"
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ./app:/app
      - ./media:/app/media
      - ./logs:/app/logs
      - ./shared:/app/shared
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15
    user: "${APP_UID:-1000}:${APP_GID:-1000}"
    ports:
      - "5433:5432"
    volumes:
      - ./deploy/db_data/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      - ./deploy/db_data:/var/lib/postgresql/data
      - ./deploy/db_backup:/backup
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
    env_file:
      - ./.env.dev
    networks:
      - app_network

  telegram-bot:
    build: ./bot/deploy
    volumes:
      - ./bot/:/app
      - ./shared:/app/shared
    depends_on:
      - web
    env_file:
      - ./bot/.env
    restart: unless-stopped

  pgbackrest_landing:
    build:
      context: ./pgbackrest
      dockerfile: ./DockerpgBackRestfile
      args:
        APP_UID: ${APP_UID:-1001}
        APP_GID: ${APP_GID:-1001}
    user: "${APP_UID:-1001}:${APP_GID:-1001}"
    environment:
      HOME: /home/pgbackrest
      PGBACKREST_CONFIG_PATH: /etc/pgbackrest
      PGDATA: /var/lib/postgresql/data
    # ports:
    #   - "2222:22"
    depends_on:
      - db
      - ./pgbackrest/.pgpass:/home/pgbackrest/.pgpass:ro
      - ./pgbackrest/config:/etc/pgbackrest
      - ./pgbackrest/logs:/var/log/pgbackrest
      - ./deploy/db_data:/var/lib/postgresql/data:rw
      - ./deploy/socket:/var/run/postgresql:ro
      - ./pgbackrest/ssh:/home/pgbackrest/.ssh/authorized_keys:ro
      - ./tmp_pgbackrest:/tmp/pgbackrest
    command: ["tail", "-f", "/dev/null"]      

networks:
  app_network:
    driver: bridge
  traefik-public:
    external: true
