# Generated by Django 5.0 on 2025-11-01 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AddressSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="адрес")),
                ("phone", models.CharField(max_length=800, verbose_name="телефон")),
                (
                    "hours_work",
                    models.CharField(max_length=800, verbose_name="режим работы"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=250, verbose_name="Ссылка на блок"),
                ),
                (
                    "geo_tag",
                    models.CharField(max_length=1200, verbose_name="Гео тэг для карты"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Адресный блок",
                "verbose_name_plural": "Адресный блок",
                "db_table": "section_address_main",
            },
        ),
        migrations.CreateModel(
            name="AddressSectionFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(blank=True, max_length=100, verbose_name="Cсылка"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=100, verbose_name="icon"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="address.addresssection",
                    ),
                ),
            ],
            options={
                "db_table": "section_address_features",
            },
        ),
    ]
