# Generated by Django 5.0 on 2025-11-01 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PriceSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Заголовок блока"),
                ),
                (
                    "desc",
                    models.CharField(max_length=800, verbose_name="Описание блока"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=250, verbose_name="Ссылка на блок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Видимость"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Цены и услуги",
                "verbose_name_plural": "Цены и услуги",
                "db_table": "section_price_main",
            },
        ),
        migrations.CreateModel(
            name="PriceSectionFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Описание"
                    ),
                ),
                (
                    "price",
                    models.CharField(blank=True, max_length=100, verbose_name="Цена"),
                ),
                (
                    "period",
                    models.CharField(blank=True, max_length=20, verbose_name="Период"),
                ),
                (
                    "is_recommended",
                    models.BooleanField(default=True, verbose_name="Рекомендуемый"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Видимость"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "services",
                    models.TextField(
                        blank=True, max_length=100, verbose_name="Список услуг"
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="price.pricesection",
                    ),
                ),
            ],
            options={
                "db_table": "section_price_features",
            },
        ),
    ]
