# Generated by Django 5.0 on 2025-11-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricesectionfeatures",
            name="services",
            field=models.TextField(
                blank=True, max_length=10000, verbose_name="Список услуг"
            ),
        ),
    ]
