# Generated by Django 5.0 on 2025-11-01 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Landing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar", models.ImageField(blank=True, upload_to="")),
                ("title", models.CharField(max_length=250, unique=True)),
                (
                    "desc",
                    models.CharField(
                        max_length=250, unique=True, verbose_name="Landing Description"
                    ),
                ),
                ("footer", models.CharField(max_length=250, unique=True)),
            ],
            options={
                "verbose_name": "Landing Settings",
                "verbose_name_plural": "Landing Settings",
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("fa-vk", "VK"),
                            ("fa-linkedin", "LinkedIn"),
                            ("fa-google", "Google"),
                            ("fa-stack-overflow", "Stack Overflow"),
                            ("fa-github", "GitHub"),
                            ("fa-youtube", "YouTube"),
                        ],
                        default="fa-vk",
                        max_length=250,
                        verbose_name="Social Media",
                    ),
                ),
                ("url_link", models.URLField(max_length=250, verbose_name="URL")),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media",
                        to="settings.landing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media",
                "verbose_name_plural": "Social Media",
            },
        ),
    ]
