# Generated by Django 5.0 on 2025-11-01 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название блока"),
                ),
                (
                    "desc",
                    models.CharField(max_length=800, verbose_name="Описание блока"),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=250,
                        unique_for_date="publish",
                        verbose_name="Ссылка на блок",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Видимость"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Страница",
                "verbose_name_plural": "Страницы",
            },
        ),
        migrations.CreateModel(
            name="AboutSectionFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True, max_length=100, verbose_name="Доп.информация"
                    ),
                ),
                (
                    "css_class",
                    models.TextField(
                        blank=True, max_length=100, verbose_name="css класс"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Доп.информация"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="about.aboutsection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AboutSectionImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="%Y/%m/%d/thumbnails"
                    ),
                ),
                (
                    "alt",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Описание картинки"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("background", "Фон"), ("icon", "Иконка")],
                        default="background",
                        max_length=10,
                        verbose_name="Тип изображения",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="about.aboutsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.CreateModel(
            name="AboutSectionWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "html_content",
                    models.TextField(blank=True, max_length=800, verbose_name="Виджет"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Видимость"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widget",
                        to="about.aboutsection",
                    ),
                ),
            ],
        ),
    ]
