# Generated by Django 5.0 on 2025-11-01 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Заголовок блока"),
                ),
                (
                    "desc",
                    models.TextField(max_length=800, verbose_name="Описание блока"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=250, verbose_name="Ссылка на блок"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Видимость"),
                ),
                ("background", models.ImageField(blank=True, upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Блок заглавный",
                "verbose_name_plural": "Блок заглавный",
                "db_table": "section_hero_main",
            },
        ),
        migrations.CreateModel(
            name="HeroSectionMarkers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Доп.информация"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="названия иноки"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Видимость"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="markers",
                        to="hero.herosection",
                        verbose_name="Связанный блок",
                    ),
                ),
            ],
            options={
                "db_table": "section_hero_markers",
            },
        ),
        migrations.DeleteModel(
            name="AboutSection",
        ),
        migrations.RemoveField(
            model_name="aboutsectionimages",
            name="section",
        ),
        migrations.RemoveField(
            model_name="aboutsectionwidget",
            name="section",
        ),
        migrations.DeleteModel(
            name="AboutSectionFeatures",
        ),
        migrations.DeleteModel(
            name="AboutSectionImages",
        ),
        migrations.DeleteModel(
            name="AboutSectionWidget",
        ),
    ]
