# Generated by Django 5.0 on 2025-11-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hero", "0002_herosection_herosectionmarkers_delete_aboutsection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="herosection",
            name="desc",
            field=models.CharField(max_length=200, verbose_name="Описание блока"),
        ),
    ]
