# Generated by Django 5.0 on 2025-11-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicesection",
            options={"verbose_name": "Блок услуг", "verbose_name_plural": "Блок услуг"},
        ),
        migrations.AlterField(
            model_name="servicesection",
            name="desc",
            field=models.CharField(max_length=800, verbose_name="Описание блока"),
        ),
    ]
