# Generated by Django 5.0 on 2026-07-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_alter_servicesection_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicesectionfeatures",
            name="desc",
            field=models.TextField(blank=True, max_length=500, verbose_name="Oписание"),
        ),
    ]
